#!/usr/bin/env bash
# Gate 6 — auto-revert the merge commit when CI on main goes red.
#
# Triggered by .github/workflows/post-merge-watchdog.yml (Phase D).
# Runs locally too if the operator wants to manually replay the watchdog.
#
# Usage: scripts/v5/auto-revert.sh <merge-sha> "<reason>"
#
# Steps per spec §4 Gate 6:
#  1. git revert -m 1 <sha> --no-edit
#  2. git push origin main
#  3. Recreate feature branch from the reverted state
#  4. Log to memory/logs/regressions/<date>.jsonl
#  5. Open GitHub issue with full context

set -euo pipefail
source "$(dirname "$0")/_lib.sh"
v5_require_cli gh
v5_require_cli jq

sha="${1:-}" reason="${2:-}"
[[ -n "$sha" && -n "$reason" ]] || v5_die "usage: auto-revert.sh <merge-sha> \"<reason>\""

cd "${V5_REPO_ROOT}"

# Find the original feature branch name from the merge commit, if available
feature_branch="$(git log --format='%s' -n1 "$sha" | sed -nE "s|^Merge pull request #[0-9]+ from [^/]+/(.+)|\1|p")"
[[ -n "$feature_branch" ]] || feature_branch="rescue-${sha:0:7}"

# 1. revert
git checkout main
git pull --ff-only origin main
v5_log "Gate 6.1 — git revert $sha"
git revert -m 1 --no-edit "$sha" || v5_die "Gate 6.1 revert failed (resolve conflicts manually)"

# 2. push
v5_log "Gate 6.2 — push main"
git push origin main || v5_die "Gate 6.2 push failed (force-push to main is hook-blocked, by design)"

# 3. recreate feature branch (from BEFORE the revert)
parent="${sha}^"
v5_log "Gate 6.3 — recreate feature branch '$feature_branch' from $parent"
git checkout -B "$feature_branch" "$parent" 2>/dev/null || true
git push -u origin "$feature_branch" 2>/dev/null || v5_warn "could not push recreated $feature_branch"
git checkout main

# 4. log
log_file="${V5_REPO_ROOT}/memory/logs/regressions/$(date -u +%F).jsonl"
mkdir -p "$(dirname "$log_file")"
printf '{"ts":"%s","sha":"%s","feature_branch":"%s","reason":%s}\n' \
  "$(date -u +%FT%TZ)" "$sha" "$feature_branch" "$(jq -Rn --arg r "$reason" '$r')" \
  >> "$log_file"
v5_log_event 6 auto-revert pass 0 "{\"sha\":\"${sha}\",\"branch\":\"${feature_branch}\"}"

# 5. open GitHub issue
issue_body=$(cat <<EOF
## Auto-revert summary

- **Merge commit reverted:** \`$sha\`
- **Feature branch recreated:** \`$feature_branch\`
- **Reason:** $reason
- **Detected at:** $(date -u +%FT%TZ)

The post-merge watchdog detected a regression on \`main\` and reverted the merge automatically. The feature branch has been recreated from the parent of the reverted commit so you can re-attempt without losing work.

## Next steps

1. Inspect what broke — see CI logs and the new entry in \`memory/logs/regressions/\`.
2. Re-run \`Fix: <directive-id>\` to retry, or merge a fix directly to the recreated branch.
3. Close this issue once green on \`main\` again.

🤖 Generated by \`scripts/v5/auto-revert.sh\`
EOF
)

gh issue create \
  --title "Auto-revert: ${feature_branch} (${sha:0:7})" \
  --body "$issue_body" \
  --label "auto-revert,regression" 2>/dev/null \
  || v5_warn "could not open GitHub issue (gh auth?)"

v5_log "Gate 6 auto-revert complete ✓"
